replicaCount: 1
image:
  repository: myregistry.azurecr.io/simple-aks-app
  tag: "latest"
containerPort: 3000
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
persistence:
  size: 1Gi
  storageClass: ""
hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
